[package]
name = "bluefin_foundation"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "09b2081498366df936abae26eea4b2d5cafb2788" }
Pyth = { local = "../submodules/pyth-crosschain/target_chains/sui/contracts"}

[addresses]
bluefin_foundation =  "0x0"
Pyth="0x8d97f1cd6ac663735be08d1d2b6d02a159e711586461306ce60a2b7a6a565a9e"