on:
  pull_request:
    types:
      - opened
      - reopened
concurrency:
  group: sui-build-cd
jobs:
  eslint_checks:
    runs-on: self-hosted # name of selfhosted EC2
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: install dependencies
        run: yarn
      - name: running ESLint
        run: yarn eslint:errors
