name: eslint-checks-pre-cd
on:
  pull_request:
    branches: [main]
    types:
      - closed
concurrency:
  group: sui-build-cd
  cancel-in-progress: true # in case merged is performed immediately
jobs:
  pr_check_pre_cd:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted # name of selfhosted EC2
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: install dependencies
        run: yarn
      - name: running ESLint
        run: yarn lint
