on:
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
jobs:
    build:
        runs-on: sui-cloud # name of selfhosted EC2
        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.SUBMODULE_PAT }}
            - name: install dependencies
              run: yarn
            - name: start building
              run: yarn build